# -*- coding: utf-8 -*-
"""frases_eventos_criação_csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1093bTnJxfT08a_4HNXqjmNTynBqBEY22

Criação de arquivo CSV somente com as frases da coluna Evento - para ser usado no módulo de Nuvem de Palavras
"""

from google.colab import drive
drive.mount('/content/drive')

# Conecta ao Google Drive
drive.mount('/content/drive', force_remount=True)

# --- CAMINHOS DOS ARQUIVOS ---
# Use o seu arquivo GRANDE E COMPLETO aqui
caminho_arquivo_grande = "/content/drive/MyDrive/TCC/TCC Final/dados/BancoVDE_2015_2024_Completo.csv"
# Nome do novo arquivo de saída. Mudei o nome para não confundir com o anterior.
caminho_arquivo_novo = "/content/drive/MyDrive/TCC/TCC Final/dados/Frequencia_Frases_Evento.csv"

print("Iniciando o processamento...")

try:
    # --- 1. CARREGAR APENAS A COLUNA 'evento' ---
    df = pd.read_csv(caminho_arquivo_grande, usecols=['evento'])
    print("Coluna 'evento' carregada.")

    # --- 2. CÁLCULO DE FREQUÊNCIA (DA FORMA CORRETA, POR FRASE) ---
    # value_counts() conta a ocorrência de cada frase única. É tudo que precisamos.
    contagem_frases = df['evento'].value_counts()

    # Cria o DataFrame final a partir da contagem
    df_frequencia = pd.DataFrame(contagem_frases).reset_index()
    df_frequencia.columns = ['Frase', 'Contagem']

    # Calcula a porcentagem de cada frase em relação ao total
    total_de_registros = df_frequencia['Contagem'].sum()
    df_frequencia['Porcentagem'] = (df_frequencia['Contagem'] / total_de_registros) * 100

    print("Cálculo de frequência de frases finalizado.")

    # --- 3. SALVAR O RESULTADO ---
    df_frequencia.to_csv(caminho_arquivo_novo, index=False)

    print("-" * 30)
    print("✅ SUCESSO!")
    print(f"Novo arquivo '{caminho_arquivo_novo.split('/')[-1]}' criado com sucesso!")
    print("Ele contém as colunas: Frase, Contagem, Porcentagem.")

except Exception as e:
    print(f"Ocorreu um erro: {e}")